# Generated by Django 3.2 on 2022-11-26 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('national_code', models.CharField(error_messages={'unique': 'یک کاربر با این کد ملی قبلا ثبت شده است'}, help_text='کد ملی خود را وارد کنید:\n', max_length=32, unique=True, validators=[utils.validators.IDNumberValidator()], verbose_name='کد ملی')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'شماره وارد شده قبلا ثبت شده است!'}, max_length=17, null=True, unique=True, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه')),
                ('is_staff', models.BooleanField(default=False, help_text='با فعال کردن این گزینه این کاربر میتواند به پنل مدیریت دسترسی داشته باشد', verbose_name='کاربر جمع آوری اطلاعات')),
                ('is_active', models.BooleanField(default=True, help_text='فعال بودن این گزینه نشان دهنده آن است که عضویت کار بر در سیستم فعال است.', verbose_name='فعال')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('last_seen', models.DateTimeField(null=True, verbose_name=' آخرین زمان فعالیت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'Users',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=150, verbose_name='نام مستعار')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.BooleanField(help_text='جنسیت میتوان مرد، زن، یا خالی باشد.', null=True, verbose_name='جنسیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
                'db_table': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.UUIDField(null=True, verbose_name='Device UUID')),
                ('last_login', models.DateTimeField(null=True, verbose_name='آخرین زمان ورود')),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, 'web'), (2, 'ios'), (3, 'android')], default=1)),
                ('device_os', models.CharField(blank=True, max_length=20, verbose_name='نوع سیستم عامل')),
                ('device_model', models.CharField(blank=True, max_length=50, verbose_name='مدل device')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='نسخه برنامه')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اطلاعات دستگاه',
                'verbose_name_plural': 'اطلاعات دستگاه ها',
                'db_table': 'user_devices',
                'unique_together': {('user', 'device_uuid')},
            },
        ),
    ]
