# Generated by Django 3.2 on 2022-11-25 16:58

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'اطلاعات دستگاه', 'verbose_name_plural': 'اطلاعات دستگاه ها'},
        ),
        migrations.AlterField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='نسخه برنامه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='با فعال کردن این گزینه این کاربر میتواند به پنل مدیریت دسترسی داشته باشد', verbose_name='کاربر جمع آوری اطلاعات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(error_messages={'unique': 'یک کاربر با این کد ملی قبلا ثبت شده است'}, help_text='کد ملی خود را وارد کنید:\n', max_length=32, unique=True, validators=[utils.validators.IDNumberValidator()], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'شماره وارد شده قبلا ثبت شده است!'}, max_length=17, null=True, unique=True, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه'),
        ),
    ]
