# Generated by Django 3.2 on 2022-11-20 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(error_messages={'unique': 'یک کاربر با این کد ملی قبلا ثبت شده است'}, help_text='کد ملی خود را وارد کنید:\n', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'هرکاربر باید کد ملی خود را وارد کند.', 'invalid')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'شماره وارد شده قبلا ثبت شده است!'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'شماره همراه خود راد وارد کنید.\n', 'invalid')], verbose_name='تلفن همراه'),
        ),
    ]
