# Generated by Django 3.2 on 2022-11-20 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221120_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'شماره وارد شده قبلا ثبت شده است!'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'شماره همراه خود راد وارد کنید.\n', 'invalid')], verbose_name='تلفن همراه\n'),
        ),
    ]
