# Generated by Django 3.2 on 2022-11-20 12:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'شماره وارد شده قبلا ثبت شده است!'}, max_length=128, null=True, region=None, unique=True, verbose_name='تلفن همراه'),
        ),
    ]
