# Generated by Django 3.2 on 2022-11-22 13:20

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(error_messages={'unique': 'یک کاربر با این کد ملی قبلا ثبت شده است'}, help_text='کد ملی خود را وارد کنید:\n', max_length=32, unique=True, validators=[utils.validators.IDNumberValidator()], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'شماره وارد شده قبلا ثبت شده است!'}, max_length=17, null=True, unique=True, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه'),
        ),
    ]
