# Generated by Django 3.2 on 2022-11-21 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(error_messages={'unique': 'یک کاربر با این کد ملی قبلا ثبت شده است'}, help_text='کد ملی خود را وارد کنید:\n', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'هرکاربر باید کد ملی خود را وارد کند.', 'invalid')], verbose_name='کد ملی'),
        ),
    ]
