# Generated by Django 3.2 on 2022-11-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_device_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'اطلاعات دستگاه', 'verbose_name_plural': 'اطلاعات دستگاه ها'},
        ),
        migrations.AlterField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='نسخه برنامه'),
        ),
    ]
