# Generated by Django 3.2 on 2022-11-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='national code')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='PosRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('father_name', models.CharField(max_length=20, verbose_name='father name')),
                ('birthday', models.CharField(max_length=15, verbose_name='date of birth')),
                ('national_card_series', models.CharField(blank=True, max_length=10, verbose_name='National card series')),
                ('birthcertificate_number', models.CharField(max_length=10, verbose_name='birth certificate number')),
                ('birthcertificate_serial', models.CharField(max_length=6, verbose_name='birth certificate serial')),
                ('birthcertificate_series', models.CharField(max_length=3, verbose_name='birth certificate series')),
                ('issued', models.CharField(max_length=50, verbose_name='issued')),
                ('State', models.CharField(max_length=50, verbose_name='state')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('store_address', models.CharField(max_length=300, verbose_name='store address')),
                ('zipcode_pos', models.CharField(max_length=10, verbose_name='zip code pos')),
                ('store_phone', models.CharField(max_length=8, verbose_name='store phone')),
                ('business_license_number', models.CharField(max_length=50, verbose_name='business license number')),
                ('tax_code', models.CharField(max_length=50, verbose_name='tax tracking code')),
                ('senf', models.CharField(max_length=25, verbose_name='senf')),
                ('Mobile', models.CharField(max_length=11, verbose_name='Mobile')),
                ('substrate', models.CharField(choices=[('Dialup', 'Dialup Type'), ('GPRS', 'GPRS Type'), ('Combo', 'Combo Type'), ('WIFI', 'WIFI Type')], default='Dialup', max_length=6, verbose_name=' substrate type')),
                ('ownership', models.CharField(choices=[('ملکی', 'نوع ملکی'), ('سرقفلی', 'نوع سرقفلی'), ('استیجاری', 'نوع استیجاری')], default='ملکی', max_length=8, verbose_name='ownership type')),
                ('leaseterm_from', models.CharField(blank=True, max_length=15, verbose_name='leaseterm from')),
                ('leaseterm_to', models.CharField(blank=True, max_length=15, verbose_name='leaseterm to')),
                ('introducer_name', models.CharField(max_length=20, verbose_name='introducer name')),
                ('introducer_lastname', models.CharField(max_length=25, verbose_name='introducer last name')),
                ('introducer_phone', models.CharField(max_length=11, verbose_name='introducer phone')),
                ('introducer_address', models.CharField(blank=True, max_length=300, verbose_name='introducer address')),
                ('first_account_number', models.CharField(max_length=20, verbose_name='first account number')),
                ('first_bank_name', models.CharField(max_length=50, verbose_name='first bank name')),
                ('first_shaba_number', models.CharField(max_length=16, verbose_name='first shaba number')),
                ('second_account_number', models.CharField(blank=True, max_length=20, verbose_name='second account number')),
                ('second_bank_name', models.CharField(blank=True, max_length=50, verbose_name='second bank name')),
                ('second_shaba_number', models.CharField(blank=True, max_length=16, verbose_name='second shaba number')),
                ('paziresh', models.BooleanField(default=False, verbose_name='paziresh')),
                ('businesslicense', models.FileField(upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='businesslicense')),
                ('leaseterm', models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='leaseterm')),
                ('ownership_document', models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='ownership document')),
                ('birthcertificate', models.FileField(upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='birth certificate')),
                ('front_nationalcard', models.FileField(upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='front national card')),
                ('back_nationalcard', models.FileField(upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='front national card')),
                ('signatureseal', models.FileField(upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='signature seal')),
                ('sabin_form_first', models.FileField(upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='sabin form first')),
                ('sabin_form_second', models.FileField(upload_to='posdocuments/%Y/%m/%d/:id/', verbose_name='sabin form second')),
                ('nameFamilyKarshenas', models.CharField(blank=True, max_length=100, verbose_name='fullname Karshenas')),
                ('cerated_time', models.DateTimeField(auto_now_add=True, verbose_name='cerated time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('national_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.user', to_field='national_code', verbose_name='national code')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poses.posregister', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Pos Request',
                'verbose_name_plural': 'Pos Requests',
                'db_table': 'posdocuments',
            },
        ),
    ]
