# Generated by Django 3.2 on 2022-11-25 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='نام')),
                ('last_name', models.CharField(max_length=25, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=20, verbose_name='نام پدر')),
                ('birth', models.DateField(verbose_name='تاریخ تولد')),
                ('mobile', models.CharField(max_length=11, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه')),
                ('national_code', models.CharField(max_length=10, validators=[utils.validators.IDNumberValidator()], verbose_name='کدملی')),
                ('national_card_series', models.CharField(blank=True, max_length=10, verbose_name='سریال پشت کارت ملی')),
                ('birthcertificate_number', models.CharField(max_length=10, verbose_name='شماره شناسنامه/کدثبتی')),
                ('birthcertificate_serial', models.CharField(max_length=6, verbose_name='سریال شناسنامه')),
                ('birthcertificate_series', models.CharField(max_length=3, verbose_name='سری شناسنامه')),
                ('issued', models.CharField(max_length=50, verbose_name='صادره از/ثبت شده در')),
                ('state', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('store_name', models.CharField(max_length=60, verbose_name='نام فروشگاه/شرکت')),
                ('store_address', models.CharField(max_length=300, verbose_name='نشانی فروشگاه/شرکت')),
                ('zipcode_pos', models.CharField(max_length=10, validators=[utils.validators.PostalCodeValidator()], verbose_name='کدپستی محل نصب')),
                ('store_phone', models.CharField(max_length=12, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن فروشگاه')),
                ('business_license_number', models.CharField(max_length=50, verbose_name='شماره پروانه کسب/شماره صنفی اجاره نامه')),
                ('tax_code', models.CharField(max_length=50, verbose_name='کد رهگیری مالیاتی')),
                ('senf', models.CharField(max_length=25, verbose_name='صنف')),
                ('substrate', models.CharField(choices=[('Dialup', 'Dialup Type'), ('GPRS', 'GPRS Type'), ('Combo', 'Combo Type'), ('WIFI', 'WIFI Type')], default='Dialup', max_length=6, verbose_name=' بستر ارتباطی')),
                ('ownership', models.CharField(choices=[('ملکی', 'نوع ملکی'), ('سرقفلی', 'نوع سرقفلی'), ('استیجاری', 'نوع استیجاری')], default='ملکی', max_length=8, verbose_name='نوع مالکیت محل نصب')),
                ('leaseterm_from', models.DateField(blank=True, verbose_name='مهلت اجاره نامه از تاریخ')),
                ('leaseterm_to', models.DateField(blank=True, verbose_name='مهلت اجاره نامه تا تاریخ')),
                ('first_introducer_name', models.CharField(max_length=20, verbose_name='نام معرف اول')),
                ('first_introducer_lastname', models.CharField(max_length=25, verbose_name='نام خانوادگی  معرف اول')),
                ('first_introducer_phone', models.CharField(max_length=12, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه  معرف اول ')),
                ('first_introducer_address', models.CharField(blank=True, max_length=300, verbose_name='نشانی محل سکونت  معرف اول ')),
                ('second_introducer_name', models.CharField(blank=True, max_length=20, verbose_name='نام  معرف دوم')),
                ('second_introducer_lastname', models.CharField(max_length=25, verbose_name='نام خانوادگی  معرف دوم')),
                ('second_introducer_phone', models.CharField(blank=True, max_length=12, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه  معرف دوم ')),
                ('second_introducer_address', models.CharField(blank=True, max_length=300, verbose_name='نشانی محل سکونت  معرف دوم ')),
                ('first_account_number', models.CharField(max_length=13, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='شماره حساب اول')),
                ('first_bank_name', models.CharField(choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='ایران زمین', max_length=50, verbose_name='نام بانک اول')),
                ('first_shaba_number', models.CharField(max_length=26, validators=[utils.validators.IBanNumberValidator()], verbose_name='شماره شبا اول')),
                ('second_account_number', models.CharField(blank=True, max_length=13, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='شماره حساب دوم')),
                ('second_bank_name', models.CharField(blank=True, choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='ایران زمین', max_length=50, verbose_name='نام بانک دوم')),
                ('second_shaba_number', models.CharField(blank=True, max_length=36, validators=[utils.validators.IBanNumberValidator()], verbose_name='شماره شبا دوم')),
                ('paziresh', models.BooleanField(default=False, verbose_name='پذیرش صحت اطلاعات')),
                ('businesslicense', models.FileField(upload_to='posdocuments/%Y/%m/%d/%s/', verbose_name='جواز کسب')),
                ('leaseterm', models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='اجاره نامه')),
                ('ownership_document', models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='سند مالکیت')),
                ('birthcertificate', models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر رو کارت ملی')),
                ('back_nationalcard', models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر پشت کارت ملی')),
                ('signatureseal', models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر مهر و امضا')),
                ('sabin_form_first', models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر صفحه اول فرم سابین')),
                ('sabin_form_second', models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر صفحه دوم فرم سابین')),
                ('cerated_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت درخواست')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('status', models.CharField(blank=True, choices=[('در انتظار بررسی ', 'در انتظار بررسی'), ('مشاهده درخواست', 'مشاهده درخواست'), ('درحال بررسی', 'درحال بررسی'), ('موافقت با درخواست', 'موافقت با درخواست'), ('رد درخواست', 'رد درخواست'), ('در حال صدور', 'در حال صدور'), ('تکمیل شده', 'تکمیل شده')], default='در انتظار بررسی', max_length=60, verbose_name='وضعیت')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posregister', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
            ],
            options={
                'verbose_name': 'درخواست کارتخوان',
                'verbose_name_plural': 'درخواست های کارتخوان',
                'db_table': 'posdocuments',
            },
        ),
    ]
