# Generated by Django 3.2 on 2022-12-03 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poses.models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=60, verbose_name='نام فروشگاه/شرکت')),
                ('store_phone', models.CharField(max_length=12, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن فروشگاه')),
                ('ownership', models.CharField(choices=[('ملکی', 'نوع ملکی'), ('سرقفلی', 'نوع سرقفلی'), ('استیجاری', 'نوع استیجاری')], default='ملکی', max_length=8, verbose_name='نوع مالکیت محل نصب')),
                ('store_address', models.CharField(max_length=300, verbose_name='نشانی فروشگاه/شرکت')),
                ('store_zipcode', models.CharField(max_length=10, validators=[utils.validators.PostalCodeValidator()], verbose_name='کدپستی محل نصب')),
                ('business_license_number', models.CharField(max_length=50, verbose_name='شماره پروانه کسب/شماره صنفی اجاره نامه')),
                ('tax_code', models.CharField(max_length=50, verbose_name='کد رهگیری مالیاتی')),
                ('senf', models.CharField(max_length=25, verbose_name='صنف')),
                ('leaseterm_from', models.DateField(blank=True, verbose_name='مهلت اجاره نامه از تاریخ')),
                ('leaseterm_to', models.DateField(blank=True, verbose_name='مهلت اجاره نامه تا تاریخ')),
                ('first_name', models.CharField(max_length=20, verbose_name='نام')),
                ('last_name', models.CharField(max_length=25, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=20, verbose_name='نام پدر')),
                ('birth', models.DateField(verbose_name='تاریخ تولد')),
                ('national_code', models.CharField(max_length=10, validators=[utils.validators.IDNumberValidator()], verbose_name='کدملی')),
                ('national_card_series', models.CharField(blank=True, max_length=10, verbose_name='سریال پشت کارت ملی')),
                ('birthcertificate_number', models.CharField(max_length=10, verbose_name='شماره شناسنامه/کدثبتی')),
                ('birthcertificate_serial', models.CharField(max_length=6, verbose_name='سریال شناسنامه')),
                ('birthcertificate_series', models.CharField(max_length=3, verbose_name='سری شناسنامه')),
                ('issued', models.CharField(max_length=50, verbose_name='صادره از/ثبت شده در')),
                ('mobile', models.CharField(max_length=11, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه')),
                ('home_phone', models.CharField(max_length=11, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن منزل')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='آدرس الکترونیک')),
                ('state', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('home_address', models.CharField(max_length=300, verbose_name='نشانی محل سکونت')),
                ('home_zipcode', models.CharField(max_length=10, validators=[utils.validators.PostalCodeValidator()], verbose_name='کدپستی محل سکونت')),
                ('first_introducer_name', models.CharField(max_length=20, verbose_name='نام معرف اول')),
                ('first_introducer_lastname', models.CharField(max_length=25, verbose_name='نام خانوادگی  معرف اول')),
                ('first_introducer_phone', models.CharField(max_length=12, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه  معرف اول ')),
                ('first_introducer_address', models.CharField(blank=True, max_length=300, verbose_name='نشانی محل سکونت  معرف اول ')),
                ('second_introducer_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام  معرف دوم')),
                ('second_introducer_lastname', models.CharField(blank=True, max_length=25, null=True, verbose_name='نام خانوادگی  معرف دوم')),
                ('second_introducer_phone', models.CharField(blank=True, max_length=12, null=True, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه  معرف دوم ')),
                ('second_introducer_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='نشانی محل سکونت  معرف دوم ')),
                ('substrate', models.CharField(choices=[('Dialup', 'DIUALUP'), ('GPRS', 'GPRS'), ('Combo', 'COMBO'), ('WIFI', 'WIFI'), ('LAN', 'LAN'), ('PC', 'PC'), ('pos سیار', 'pos سیار'), ('کیوسک دیواری', 'کیوسک دیواری'), ('کیوسک ایستاده', 'کیوسک ایستاده')], default='Dialup', max_length=13, verbose_name=' بستر ارتباطی')),
                ('first_bank_name', models.CharField(choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='ایران زمین', max_length=50, verbose_name='نام بانک اول')),
                ('branch_bank_name', models.CharField(max_length=25, verbose_name='نام شعبه')),
                ('branch_bank_number', models.IntegerField(verbose_name='کد شعبه ')),
                ('account_number', models.CharField(max_length=13, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='شماره حساب ')),
                ('shaba_number', models.CharField(max_length=26, validators=[utils.validators.IBanNumberValidator()], verbose_name='شماره شبا')),
                ('paziresh', models.BooleanField(default=False, verbose_name='پذیرش صحت اطلاعات')),
                ('psp', models.CharField(choices=[('پرداخت نوين آرين', 'پرداخت نوين آرين'), ('سابين سامان', 'سابين سامان'), ('سابين پارسيان', 'سابين پارسيان'), ('پرداخت سپهر صادرات', 'پرداخت سپهر صادرات'), ('فن آوا كارت', 'فن آوا كارت')], default='پرداخت نوين آرين', max_length=50, verbose_name='نام بانک اول')),
                ('permission_document', models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='جواز كسب/ اجاره نامه / سند مالكيت / استشهاد نامه ')),
                ('birthcertificate_document', models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر دو صفحه اول شناسنامه')),
                ('nationalcard_document', models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر پشت  و رو کارت ملی')),
                ('signatureseal', models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر مهر و امضا')),
                ('acceptance_form', models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر دو صفحه فرم پذيرندگي')),
                ('cerated_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت درخواست')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('status', models.CharField(blank=True, choices=[('ثبت درخواست ', 'ثبت درخواست'), ('مشاهده شد', 'مشاهده شد'), ('درحال بررسی', 'درحال بررسی'), ('رد درخواست (نامرتبط بودن صنف)', 'رد از طرف شرکت (نامرتبط بودن صنف)'), ('ثبت شاپرک', 'ثبت شاپرک'), ('رد به علت نقص مدارک', 'رد به علت نقص مدارک'), ('اختصاص ترمینال', 'اختصاص ترمینال'), ('نصب شد', 'نصب شد')], default='ثبت درخواست', max_length=60, verbose_name='وضعیت')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posregister', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
            ],
            options={
                'verbose_name': 'درخواست کارتخوان',
                'verbose_name_plural': 'درخواست های کارتخوان',
                'db_table': 'posdocuments',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_cheque', models.CharField(max_length=20, verbose_name='شماره چک صیادی / سفته')),
                ('date_cheque', models.DateField(verbose_name='تاریخ سرسید')),
                ('bankName_cheque', models.CharField(max_length=25, verbose_name='نام یانک')),
                ('amount_number_cheque', models.CharField(max_length=50, validators=[utils.validators.AmountChequeValidator()], verbose_name=' مبلغ چك / سفته به رقم')),
                ('amount_letter_cheque', models.CharField(max_length=100, verbose_name='مبلغ چك / سفته به حروف')),
                ('account_owner_cheque', models.CharField(max_length=50, verbose_name='نام صاحب حساب')),
                ('iban_cheque', models.CharField(max_length=36, validators=[utils.validators.IBanNumberValidator()], verbose_name='شماره شبا')),
                ('front_nationalcard', models.FileField(upload_to=poses.models.Cheque.get_media_file_name, verbose_name='تصویر رو کارت ملی')),
                ('posreg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poses.posregister')),
            ],
            options={
                'verbose_name': 'اطلاعات چک',
                'verbose_name_plural': 'اطلاعات چک ها ',
                'db_table': 'Cheque',
            },
        ),
    ]
