# Generated by Django 3.2 on 2022-11-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='birthday',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_bank_name',
            field=models.CharField(choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='', max_length=50, verbose_name='first bank name'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm_from',
            field=models.DateField(blank=True, verbose_name='leaseterm from'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm_to',
            field=models.DateField(blank=True, verbose_name='leaseterm to'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='national code'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.user', to_field='national_code', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_account_number',
            field=models.CharField(blank=True, choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='', max_length=20, verbose_name='second account number'),
        ),
    ]
