# Generated by Django 3.2 on 2022-11-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Login',
        ),
    ]
