# Generated by Django 3.2 on 2022-12-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='posreg',
        ),
        migrations.AddField(
            model_name='cheque',
            name='possegister',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='poses.posregister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posregister',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
