# Generated by Django 3.2 on 2022-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='second_introducer_lastname',
            field=models.CharField(blank=True, max_length=25, verbose_name='نام خانوادگی  معرف دوم'),
        ),
    ]
