# Generated by Django 3.2 on 2022-11-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posregister',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
