# Generated by Django 3.2 on 2022-11-27 07:07

from django.db import migrations, models
import poses.models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0002_alter_posregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='back_nationalcard',
            field=models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر پشت کارت ملی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birthcertificate',
            field=models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر دو صفحه اول شناسنامه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='جواز کسب'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='front_nationalcard',
            field=models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر رو کارت ملی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm',
            field=models.FileField(blank=True, upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='اجاره نامه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='ownership_document',
            field=models.FileField(blank=True, upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='سند مالکیت'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_first',
            field=models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر صفحه اول فرم سابین'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_second',
            field=models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر صفحه دوم فرم سابین'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='signatureseal',
            field=models.FileField(upload_to=poses.models.PosRegister.get_media_file_name, verbose_name='تصویر مهر و امضا'),
        ),
    ]
