# Generated by Django 3.2 on 2022-12-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0002_auto_20221204_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='front_nationalcard',
            new_name='cheque_document',
        ),
    ]
