# Generated by Django 3.2 on 2022-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0002_alter_posregister_second_introducer_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='جواز کسب'),
        ),
    ]
