# Generated by Django 3.2 on 2022-11-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poses', '0003_alter_posregister_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='posregister',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='posregisters', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posregister',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='national code'),
        ),
    ]
