# Generated by Django 3.2 on 2022-11-27 07:23

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0003_auto_20221127_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='second_introducer_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نشانی محل سکونت  معرف دوم '),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_introducer_lastname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='نام خانوادگی  معرف دوم'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_introducer_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام  معرف دوم'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_introducer_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه  معرف دوم '),
        ),
    ]
