# Generated by Django 3.2 on 2022-11-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0003_auto_20221107_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%id/', verbose_name='businesslicense'),
        ),
    ]
