# Generated by Django 3.2 on 2022-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0004_auto_20221205_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
