# Generated by Django 3.2 on 2022-12-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0005_alter_posregister_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='possegister',
            new_name='posregister',
        ),
    ]
