# Generated by Django 3.2 on 2022-11-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0005_auto_20221107_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='back_nationalcard',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='front national card'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birthcertificate',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='birth certificate'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='businesslicense'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='front_nationalcard',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='front national card'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='leaseterm'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='ownership_document',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='ownership document'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_first',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='sabin form first'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_second',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='sabin form second'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='signatureseal',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%pk/', verbose_name='signature seal'),
        ),
    ]
