# Generated by Django 3.2 on 2022-11-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0006_auto_20221107_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='posregister',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poses.user', to_field='national_code', verbose_name='parent'),
        ),
    ]
