# Generated by Django 3.2 on 2022-11-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0007_posregister_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='back_nationalcard',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/', verbose_name='front national card'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birthcertificate',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/', verbose_name='birth certificate'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/', verbose_name='businesslicense'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_bank_name',
            field=models.CharField(choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='ایران زمین', max_length=15, verbose_name='first bank name'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='front_nationalcard',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/', verbose_name='front national card'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/', verbose_name='leaseterm'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='ownership_document',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/', verbose_name='ownership document'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_first',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/', verbose_name='sabin form first'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_second',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/', verbose_name='sabin form second'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='signatureseal',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/', verbose_name='signature seal'),
        ),
    ]
