# Generated by Django 3.2 on 2022-11-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poses', '0007_alter_posregister_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='national_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posregisters', to=settings.AUTH_USER_MODEL, verbose_name='national code'),
        ),
    ]
