# Generated by Django 3.2 on 2022-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0008_alter_posregister_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='national code'),
        ),
    ]
