# Generated by Django 3.2 on 2022-11-21 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poses', '0009_alter_posregister_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='posregister',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='posregisters', to='users.user'),
            preserve_default=False,
        ),
    ]
