# Generated by Django 3.2 on 2022-11-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0009_alter_posregister_first_bank_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posregister',
            options={'verbose_name': 'Card reader request', 'verbose_name_plural': 'Card reader requests'},
        ),
    ]
