# Generated by Django 3.2 on 2022-12-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0009_alter_cheque_posregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='posregister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='poses.posregister'),
        ),
    ]
