# Generated by Django 3.2 on 2022-11-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0010_alter_posregister_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posregister',
            options={'verbose_name': 'Pos Request', 'verbose_name_plural': 'Pos Requests'},
        ),
    ]
