# Generated by Django 3.2 on 2022-11-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0010_posregister_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posregister',
            name='user',
        ),
    ]
