# Generated by Django 3.2 on 2022-11-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0011_alter_posregister_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posregister',
            options={'verbose_name': 'Card reader request', 'verbose_name_plural': 'Card reader request'},
        ),
    ]
