# Generated by Django 3.2 on 2022-11-22 07:54

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0012_auto_20221121_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[utils.validators.IDNumberValidator()], verbose_name='national code'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_account_number',
            field=models.CharField(max_length=20, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='first account number'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_shaba_number',
            field=models.CharField(max_length=16, validators=[utils.validators.IBanNumberValidator()], verbose_name='first shaba number'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='introducer_phone',
            field=models.CharField(max_length=11, validators=[utils.validators.PhonNumberValidator()], verbose_name='introducer phone'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='mobile',
            field=models.CharField(max_length=11, validators=[utils.validators.PhonNumberValidator()], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='national_code',
            field=models.CharField(max_length=10, validators=[utils.validators.IDNumberValidator()], verbose_name='national code'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_account_number',
            field=models.CharField(blank=True, max_length=20, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='second account number'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_bank_name',
            field=models.CharField(blank=True, choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='ایران زمین', max_length=50, verbose_name='second bank name'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_shaba_number',
            field=models.CharField(blank=True, max_length=16, validators=[utils.validators.IBanNumberValidator()], verbose_name='second shaba number'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='zipcode_pos',
            field=models.CharField(max_length=10, validators=[utils.validators.PostalCodeValidator()], verbose_name='zip code pos'),
        ),
    ]
