# Generated by Django 3.2 on 2022-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0013_auto_20221107_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='status',
            field=models.CharField(blank=True, choices=[('در انتظار بررسی ', 'در انتظار بررسی'), ('مشاهده درخواست', 'مشاهده درخواست'), ('درحال بررسی', 'درحال بررسی'), ('موافقت با درخواست', 'موافقت با درخواست'), ('رد درخواست', 'رد درخواست'), ('در حال صدور', 'در حال صدور'), ('تکمیل شده', 'تکمیل شده')], default='در انتظار بررسی', max_length=60, verbose_name='status'),
        ),
    ]
