# Generated by Django 3.2 on 2022-11-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0015_alter_posregister_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posregister',
            old_name='parent',
            new_name='user',
        ),
    ]
