# Generated by Django 3.2 on 2022-11-22 09:11

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0015_auto_20221122_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%(national_code)/%S/', verbose_name='businesslicense'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_account_number',
            field=models.CharField(max_length=13, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='first account number'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_account_number',
            field=models.CharField(blank=True, max_length=13, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='second account number'),
        ),
    ]
