# Generated by Django 3.2 on 2022-11-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0016_auto_20221122_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/%(national_code)/%S/', verbose_name='leaseterm'),
        ),
    ]
