# Generated by Django 3.2 on 2022-11-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0016_rename_parent_posregister_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posregisters', to='poses.user', verbose_name='parent'),
        ),
    ]
