# Generated by Django 3.2 on 2022-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0017_alter_posregister_leaseterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm',
            field=models.FileField(blank=True, upload_to='posregister/%Y/%m/%d/user_<django.db.models.query_utils.DeferredAttribute object at 0x00000210752B1060>/%M/', verbose_name='leaseterm'),
        ),
    ]
