# Generated by Django 3.2 on 2022-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0020_alter_posregister_leaseterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='businesslicense'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/<django.db.models.fields.CharField>/%S/', verbose_name='leaseterm'),
        ),
    ]
