# Generated by Django 3.2 on 2022-11-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0023_alter_posregister_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posregister',
            table='posdocument',
        ),
    ]
