# Generated by Django 3.2 on 2022-11-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0025_alter_posregister_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
