# Generated by Django 3.2 on 2022-11-24 05:19

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0026_delete_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posregister',
            options={'verbose_name': 'درخواست کارتخوان', 'verbose_name_plural': 'درخواست های کارتخوان'},
        ),
        migrations.AlterField(
            model_name='posregister',
            name='back_nationalcard',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر پشت کارت ملی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birth',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birthcertificate',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر دو صفحه اول شناسنامه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birthcertificate_number',
            field=models.CharField(max_length=10, verbose_name='شماره شناسنامه/کدثبتی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birthcertificate_serial',
            field=models.CharField(max_length=6, verbose_name='سریال شناسنامه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='birthcertificate_series',
            field=models.CharField(max_length=3, verbose_name='سری شناسنامه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='business_license_number',
            field=models.CharField(max_length=50, verbose_name='شماره پروانه کسب/شماره صنفی اجاره نامه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='جواز کسب'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='cerated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت درخواست'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='father_name',
            field=models.CharField(max_length=20, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_account_number',
            field=models.CharField(max_length=13, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='شماره حساب اول'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_bank_name',
            field=models.CharField(choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='ایران زمین', max_length=50, verbose_name='نام بانک اول'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='first_shaba_number',
            field=models.CharField(max_length=26, validators=[utils.validators.IBanNumberValidator()], verbose_name='شماره شبا اول'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='front_nationalcard',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر رو کارت ملی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='introducer_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='نشانی محل سکونت معرف '),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='introducer_lastname',
            field=models.CharField(max_length=25, verbose_name='نام خانوادگی معرف'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='introducer_name',
            field=models.CharField(max_length=20, verbose_name='نام معرف'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='introducer_phone',
            field=models.CharField(max_length=12, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه معرف '),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='issued',
            field=models.CharField(max_length=50, verbose_name='صادره از/ثبت شده در'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='اجاره نامه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm_from',
            field=models.DateField(blank=True, verbose_name='مهلت اجاره نامه از تاریخ'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='leaseterm_to',
            field=models.DateField(blank=True, verbose_name='مهلت اجاره نامه تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='mobile',
            field=models.CharField(max_length=11, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='nameFamilyKarshenas',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام کارشناس'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='national_card_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='سریال پشت کارت ملی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='national_code',
            field=models.CharField(max_length=10, validators=[utils.validators.IDNumberValidator()], verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='ownership',
            field=models.CharField(choices=[('ملکی', 'نوع ملکی'), ('سرقفلی', 'نوع سرقفلی'), ('استیجاری', 'نوع استیجاری')], default='ملکی', max_length=8, verbose_name='نوع مالکیت محل نصب'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='ownership_document',
            field=models.FileField(blank=True, upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='سند مالکیت'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='paziresh',
            field=models.BooleanField(default=False, verbose_name='پذیرش صحت اطلاعات'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_first',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر صفحه اول فرم سابین'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='sabin_form_second',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر صفحه دوم فرم سابین'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_account_number',
            field=models.CharField(blank=True, max_length=13, validators=[utils.validators.BankAccountNumberValidator()], verbose_name='شماره حساب دوم'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_bank_name',
            field=models.CharField(blank=True, choices=[('ایران زمین', 'نوع ایران زمین'), ('آینده', 'نوع آینده'), ('پست بانک', 'نوع پست بانک'), ('خاورمیانه', 'نوع خاورمیانه'), ('دی', 'نوع دی'), ('رفاه', 'نوع رفاه'), ('سامان', 'نوع سامان'), ('شهر', 'نوع شهر'), ('صادرات', 'نوع صادرات'), ('کشاورزی', 'نوع کشاورزی'), ('گردشگری', 'نوع گردشگری'), ('مسکن', 'نوع مسکن'), ('ملی', 'نوع ملی'), ('اقتصاد نوین', 'نوع اقتصاد نوین'), ('پارسیان', 'نوع پارسیان'), ('تجارت', 'نوع تجارت'), ('توسعه تعاون', 'نوع توسعه تعاون'), ('سپه', 'نوع سپه'), ('سرمایه', 'نوع سرمایه'), ('سینا', 'نوع سینا'), ('صنعت و معدن', 'صنعت و معدن'), ('کار آفرین', 'کار آفرین')], default='ایران زمین', max_length=50, verbose_name='نام بانک دوم'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='second_shaba_number',
            field=models.CharField(blank=True, max_length=36, validators=[utils.validators.IBanNumberValidator()], verbose_name='شماره شبا دوم'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='senf',
            field=models.CharField(max_length=25, verbose_name='صنف'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='signatureseal',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%S/', verbose_name='تصویر مهر و امضا'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='state',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='status',
            field=models.CharField(blank=True, choices=[('در انتظار بررسی ', 'در انتظار بررسی'), ('مشاهده درخواست', 'مشاهده درخواست'), ('درحال بررسی', 'درحال بررسی'), ('موافقت با درخواست', 'موافقت با درخواست'), ('رد درخواست', 'رد درخواست'), ('در حال صدور', 'در حال صدور'), ('تکمیل شده', 'تکمیل شده')], default='در انتظار بررسی', max_length=60, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='store_address',
            field=models.CharField(max_length=300, verbose_name='نشانی فروشگاه/شرکت'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='store_phone',
            field=models.CharField(max_length=12, validators=[utils.validators.PhonNumberValidator()], verbose_name='تلفن فروشگاه'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='substrate',
            field=models.CharField(choices=[('Dialup', 'Dialup Type'), ('GPRS', 'GPRS Type'), ('Combo', 'Combo Type'), ('WIFI', 'WIFI Type')], default='Dialup', max_length=6, verbose_name=' بستر ارتباطی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='tax_code',
            field=models.CharField(max_length=50, verbose_name='کد رهگیری مالیاتی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='zipcode_pos',
            field=models.CharField(max_length=10, validators=[utils.validators.PostalCodeValidator()], verbose_name='کدپستی محل نصب'),
        ),
    ]
