# Generated by Django 3.2 on 2022-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0027_auto_20221124_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posregister',
            name='businesslicense',
            field=models.FileField(upload_to='posdocuments/%Y/%m/%d/%s/', verbose_name='جواز کسب'),
        ),
    ]
